### ISSUE TITLE
Error: arm/arm: Unable to sample any valid states for goal tree

### ISSUE THREAD

**Issue by waedbara** [Unity-Technologies/Robotics-Object-Pose-Estimation#63] opened 2022-09-22 13:04 UTC
Hello there,
I am trying to build robotics-object-pose-estimation project in my local machine but after I am running ROS server and try to click on pose estimation button in unity it return error "Error: arm/arm: Unable to sample any valid states for goal tree" Any help?
 Thanks

**Console logs / stack traces**

[ERROR] [1663850579.670529300]: arm/arm: Unable to sample any valid states for goal tree

**Screenshots**

![Screenshot (1)](https://user-images.githubusercontent.com/20625434/191756242-3bdf09f3-d436-40f5-9242-b8680e904846.png)

**Environment (please complete the following information, where applicable):**

- Unity Version: [e.g. Unity 2021.3.9f1]
- Unity machine OS + version: [e.g. Windows 11]
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Noetic]
- ROS–Unity communication: [e.g. Docker]
- Package branches or versions: [e.g. `com.unity.perception@0.8.0-preview.3`]

**Comment by at669** [comment] 2022-09-26 17:51
Hi, thanks for reaching out. I can't reproduce this issue locally—although the project instructions suggest a 2020.2 Unity version, my local upgrade to 2021.3 still runs as expected. In your case, I would suggest running the [Quick Demo](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/Documentation/quick_demo_full.md) on your machine to see if the same issue comes up. Let us know if the issue persists.

**Comment by waedbara** [comment] 2022-09-26 18:22
Hi Amanda 
Yesterday I was tried  this version 2020.2 and it was worked... finally 💯but version Unity 2021.3.9f1 not worked
Thanks

**Comment by at669** [comment] 2022-09-26 18:27
Thanks for the quick response! 2020.2 is the supported version for this project, I'm glad to hear it worked out. I will close this issue as it has been resolved.

**Closed as completed by at669** 2022-09-26 18:27 UTC

**Comment by waedbara** [comment] 2022-09-26 20:05
Thanks , Please mention the supported version in the main repo page.
