### ISSUE TITLE
Could NOT find ros_tcp_endpoint

### ISSUE THREAD

**Issue by JoSharon** [Unity-Technologies/Robotics-Object-Pose-Estimation#21] opened 2021-03-09 06:47 UTC
In Pick-and-Place with Object Pose Estimation: Quick Demo, Set Up the ROS Side, Step2.
use "docker build -t unity-robotics:pose-estimation -f docker/Dockerfile ."
and show error. What should I do? Thanks!

E:\UnityProjects\2020\Robotics-Object-Pose-Estimation>docker build -t unity-robotics:pose-estimation -f docker/Dockerfile .
[+] Building 14.2s (17/18)
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 1.41kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ros:noetic-ros-base                                             5.1s
 => [internal] load build context                                                                                  2.0s
 => => transferring context: 110.51MB                                                                              1.9s
 => [ 1/14] FROM docker.io/library/ros:noetic-ros-base@sha256:68085c6624824d5ad276450d21377d34dccdc75785707f244a9  0.0s
 => CACHED [ 2/14] RUN sudo apt-get update && sudo apt-get install -y vim iputils-ping net-tools python3-pip ros-  0.0s
 => CACHED [ 3/14] RUN sudo -H pip3 --no-cache-dir install rospkg numpy jsonpickle scipy easydict torch==1.7.1+cu  0.0s
 => CACHED [ 4/14] WORKDIR /catkin_ws                                                                              0.0s
 => CACHED [ 5/14] COPY ./ROS/src/moveit_msgs /catkin_ws/src/moveit_msgs                                           0.0s
 => CACHED [ 6/14] COPY ./ROS/src/robotiq /catkin_ws/src/robotiq                                                   0.0s
 => CACHED [ 7/14] COPY ./ROS/src/ros_tcp_endpoint /catkin_ws/src/ros_tcp_endpoint                                 0.0s
 => CACHED [ 8/14] COPY ./ROS/src/universal_robot /catkin_ws/src/universal_robot                                   0.0s
 => [ 9/14] COPY ./ROS/src/ur3_moveit /catkin_ws/src/ur3_moveit                                                    1.1s
 => [10/14] COPY ./docker/set-up-workspace /setup.sh                                                               0.1s
 => [11/14] COPY docker/tutorial /                                                                                 0.1s
 => [12/14] RUN /bin/bash -c "find /catkin_ws -type f -print0 | xargs -0 dos2unix"                                 1.0s
 => ERROR [13/14] RUN dos2unix /tutorial && dos2unix /setup.sh && chmod +x /setup.sh && /setup.sh && rm /setup.sh  4.8s
------
 > [13/14] RUN dos2unix /tutorial && dos2unix /setup.sh && chmod +x /setup.sh && /setup.sh && rm /setup.sh:
#17 0.402 dos2unix: converting file /tutorial to Unix format...
#17 0.406 dos2unix: converting file /setup.sh to Unix format...
#17 1.304 -- The C compiler identification is GNU 9.3.0
#17 1.548 -- The CXX compiler identification is GNU 9.3.0
#17 1.567 -- Check for working C compiler: /usr/bin/cc
#17 1.694 -- Check for working C compiler: /usr/bin/cc -- works
#17 1.696 -- Detecting C compiler ABI info
#17 1.779 -- Detecting C compiler ABI info - done
#17 1.799 -- Detecting C compile features
#17 1.800 -- Detecting C compile features - done
#17 1.806 -- Check for working CXX compiler: /usr/bin/c++
#17 1.895 -- Check for working CXX compiler: /usr/bin/c++ -- works
#17 1.897 -- Detecting CXX compiler ABI info
#17 1.987 -- Detecting CXX compiler ABI info - done
#17 2.007 -- Detecting CXX compile features
#17 2.008 -- Detecting CXX compile features - done
#17 2.376 -- Using CATKIN_DEVEL_PREFIX: /catkin_ws/devel
#17 2.377 -- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
#17 2.377 -- This workspace overlays: /opt/ros/noetic
#17 2.408 -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3")
#17 2.409 -- Using PYTHON_EXECUTABLE: /usr/bin/python3
#17 2.409 -- Using Debian Python package layout
#17 2.447 -- Found PY_em: /usr/lib/python3/dist-packages/em.py
#17 2.447 -- Using empy: /usr/lib/python3/dist-packages/em.py
#17 2.585 -- Using CATKIN_ENABLE_TESTING: ON
#17 2.585 -- Call enable_testing()
#17 2.588 -- Using CATKIN_TEST_RESULTS_DIR: /catkin_ws/build/test_results
#17 3.003 -- Forcing gtest/gmock from source, though one was otherwise available.
#17 3.003 -- Found gtest sources under '/usr/src/googletest': gtests will be built
#17 3.003 -- Found gmock sources under '/usr/src/googletest': gmock will be built
#17 3.033 -- Found PythonInterp: /usr/bin/python3 (found version "3.8.5")
#17 3.036 -- Found Threads: TRUE
#17 3.052 -- Using Python nosetests: /usr/bin/nosetests3
#17 3.119 -- catkin 0.8.9
#17 3.119 -- BUILD_SHARED_LIBS is on
#17 3.289 -- BUILD_SHARED_LIBS is on
#17 3.289 -- Using CATKIN_WHITELIST_PACKAGES: moveit_msgs;ros_tcp_endpoint;ur3_moveit;robotiq_2f_140_gripper_visualization;ur_description;ur_gazebo
#17 4.211 -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#17 4.211 -- ~~  traversing 1 packages in topological order:
#17 4.211 -- ~~  - ur3_moveit
#17 4.211 -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#17 4.212 -- +++ processing catkin package: 'ur3_moveit'
#17 4.212 -- ==> add_subdirectory(ur3_moveit)
#17 4.771 -- Could NOT find ros_tcp_endpoint (missing: ros_tcp_endpoint_DIR)
#17 4.771 -- Could not find the required component 'ros_tcp_endpoint'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
#17 4.771 CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
#17 4.771   Could not find a package configuration file provided by "ros_tcp_endpoint"
#17 4.771   with any of the following names:
#17 4.771
#17 4.771     ros_tcp_endpointConfig.cmake
#17 4.771     ros_tcp_endpoint-config.cmake
#17 4.771
#17 4.771   Add the installation prefix of "ros_tcp_endpoint" to CMAKE_PREFIX_PATH or
#17 4.771   set "ros_tcp_endpoint_DIR" to a directory containing one of the above
#17 4.771   files.  If "ros_tcp_endpoint" provides a separate development package or
#17 4.771   SDK, be sure it has been installed.
#17 4.771 Call Stack (most recent call first):
#17 4.771   ur3_moveit/CMakeLists.txt:13 (find_package)
#17 4.771
#17 4.772
#17 4.775 -- Configuring incomplete, errors occurred!
#17 4.775 See also "/catkin_ws/build/CMakeFiles/CMakeOutput.log".
#17 4.775 See also "/catkin_ws/build/CMakeFiles/CMakeError.log".
#17 4.782 Base path: /catkin_ws
#17 4.782 Source space: /catkin_ws/src
#17 4.782 Build space: /catkin_ws/build
#17 4.782 Devel space: /catkin_ws/devel
#17 4.782 Install space: /catkin_ws/install
#17 4.782 Creating symlink "/catkin_ws/src/CMakeLists.txt" pointing to "/opt/ros/noetic/share/catkin/cmake/toplevel.cmake"
#17 4.782 ####
#17 4.782 #### Running command: "cmake /catkin_ws/src -DCATKIN_WHITELIST_PACKAGES=moveit_msgs;ros_tcp_endpoint;ur3_moveit;robotiq_2f_140_gripper_visualization;ur_description;ur_gazebo -DCATKIN_DEVEL_PREFIX=/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/catkin_ws/install -G Unix Makefiles" in "/catkin_ws/build"
#17 4.782 ####
#17 4.782 Invoking "cmake" failed
------
executor failed running [/bin/sh -c dos2unix /tutorial && dos2unix /setup.sh && chmod +x /setup.sh && /setup.sh && rm /setup.sh]: exit code: 1

**Comment by nullbyte91** [comment] 2021-03-09 06:57
@JoSharon I believe this docker file might not support Window env since the path given in Unix format

**Comment by mrpropellers** [comment] 2021-03-09 23:45
This file should work on Windows! Most processes are agnostic to Windows vs. *nix style path separators. @JoSharon can you double-check that you've checked out the `ros_tcp_endpoint` submodule into the project?  You should see a directory full of code [here](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/tree/main/ROS/src). If not, you may need to run `git submodule update --init --recursive` from within your local copy of the repository in order to checkout the requisite submodules that CMake cannot find here.  Let me know if that does not fix the issue.

**Comment by mrpropellers** [comment] 2021-03-12 20:14
Hi @JoSharon -- has the submodule checkout resolved this issue?  If there are no additional complications I'd like to close this issue.

**Closed** 2021-03-15 18:53 UTC

**Comment by JoSharon** [comment] 2021-04-13 08:41
> Hi @JoSharon -- has the submodule checkout resolved this issue? If there are no additional complications I'd like to close this issue.
It works! Thank you! 
I don't know why submodule files are missing in clone zip of "Robotics-Object-Pose-Estimation",
and need to clone each submodule and copy into "Robotics-Object-Pose-Estimation".

**Comment by JoSharon** [comment] 2021-04-13 08:42
> Hi @JoSharon -- has the submodule checkout resolved this issue? If there are no additional complications I'd like to close this issue.

It works! Thank you!
I don't know why submodule files are missing in clone zip of "Robotics-Object-Pose-Estimation",
and need to clone each submodule and copy into "Robotics-Object-Pose-Estimation".

**Comment by etriantafyllidis** [comment] 2022-06-23 11:44
Similar issue here. However, I can confirm the solution from @mrpropellers from above, `git submodule update --init --recursive` fixed it for me :)
